---
- name: Deploy a VM from a template
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/all
  vars:
    vcenter_hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    vcenter_username: '{{ lookup("env", "VMWARE_USER") }}'
    vcenter_password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
  
  tasks:

    - name: Debug variables
      ansible.builtin.debug:
        msg: "{{ vm_envs }}"

    - name: Debug variables
      ansible.builtin.debug:
        msg: "{{ vm_envs[ vm_env ]['datacenter'] }}"

    - name: Clone a virtual machine from Linux template and customize
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vm_envs[ vm_env ]['datacenter'] }}"
        cluster: "{{ vm_envs[ vm_env ]['vm_cluster'] }}"
        folder: "{{ vm_envs[ vm_env ]['vm_folder'] }}"
        template: "{{ vm_template }}"
        name: "{{ vm_name }}"
        networks:
          - name: '{{ vm_network }}'
            type: static
            device_type: vmxnet3
            ip: "{{ vm_ip }}"
            netmask: 255.255.255.0
            gateway: 192.168.160.1
            # dns_servers:
            #   - 8.8.8.8
            # domain: entrenchedrealist.com
        wait_for_ip_address: true
        wait_for_ip_address_timeout: 120
        customization:
          domain: "{{ vm_guest_domain }}"
          dns_servers:
            8.8.8.8
          # dns_suffix:
          #   example.com
          #   example2.com
          # script_text: |
          #   #!/bin/bash
          #   #touch /tmp/touch-from-playbook
